import StudyCalendarTemplate from '../components/StudyCalendarTemplate'

const DAYS = [
  // Week 1 — Arrays + Two Pointers + Bit
  { day: 1,  label: 'Arrays I',           problems: [{ num: 1,   title: 'Two Sum',                            path: '/problems/two-sum',                                difficulty: 'Easy',   category: 'Array'          }, { num: 121,  title: 'Best Time to Buy and Sell Stock',        path: '/problems/best-time-buy-sell-stock',               difficulty: 'Easy',   category: 'Array'          }]},
  { day: 2,  label: 'Arrays II',          problems: [{ num: 217, title: 'Contains Duplicate',                 path: '/problems/contains-duplicate',                     difficulty: 'Easy',   category: 'Array'          }, { num: 238,  title: 'Product of Array Except Self',           path: '/problems/product-of-array-except-self',           difficulty: 'Medium', category: 'Array'          }]},
  { day: 3,  label: 'Arrays III',         problems: [{ num: 53,  title: 'Maximum Subarray',                   path: '/problems/maximum-subarray',                       difficulty: 'Medium', category: 'Array'          }, { num: 152,  title: 'Maximum Product Subarray',               path: '/problems/maximum-product-subarray',               difficulty: 'Medium', category: 'Array'          }]},
  { day: 4,  label: 'Arrays IV',          problems: [{ num: 33,  title: 'Search in Rotated Sorted Array',     path: '/problems/search-rotated-sorted-array',            difficulty: 'Medium', category: 'Array'          }, { num: 15,   title: '3Sum',                                   path: '/problems/3sum',                                   difficulty: 'Medium', category: 'Array'          }]},
  { day: 5,  label: 'Arrays V',           problems: [{ num: 11,  title: 'Container With Most Water',          path: '/problems/container-with-most-water',              difficulty: 'Medium', category: 'Array'          }]},
  { day: 6,  label: 'Two Pointers',       problems: [{ num: 680, title: 'Valid Palindrome II',                path: '/problems/valid-palindrome-ii',                    difficulty: 'Easy',   category: 'Two Pointers'   }, { num: 167,  title: 'Two Sum II',                              path: '/problems/two-sum-ii',                             difficulty: 'Medium', category: 'Two Pointers'   }]},
  { day: 7,  label: 'Bit Manipulation I', problems: [{ num: 371, title: 'Sum of Two Integers',               path: '/problems/sum-of-two-integers',                    difficulty: 'Medium', category: 'Bit Manipulation'}, { num: 191,  title: 'Number of 1 Bits',                        path: '/problems/number-of-1-bits',                       difficulty: 'Easy',   category: 'Bit Manipulation'}]},
  // Week 2 — Bit + DP
  { day: 8,  label: 'Bit Manipulation II',problems: [{ num: 190, title: 'Reverse Bits',                       path: '/problems/reverse-bits',                           difficulty: 'Easy',   category: 'Bit Manipulation'}, { num: 338,  title: 'Counting Bits',                           path: '/problems/counting-bits',                          difficulty: 'Easy',   category: 'Bit Manipulation'}]},
  { day: 9,  label: 'DP I',               problems: [{ num: 70,  title: 'Climbing Stairs',                    path: '/problems/climbing-stairs',                        difficulty: 'Easy',   category: 'Dynamic Programming'}, { num: 322, title: 'Coin Change',                             path: '/problems/coin-change',                            difficulty: 'Medium', category: 'Dynamic Programming'}]},
  { day: 10, label: 'DP II',              problems: [{ num: 198, title: 'House Robber',                       path: '/problems/house-robber',                           difficulty: 'Medium', category: 'Dynamic Programming'}, { num: 213, title: 'House Robber II',                         path: '/problems/house-robber-ii',                        difficulty: 'Medium', category: 'Dynamic Programming'}]},
  { day: 11, label: 'DP III',             problems: [{ num: 300, title: 'Longest Increasing Subsequence',     path: '/problems/longest-increasing-subsequence',         difficulty: 'Medium', category: 'Dynamic Programming'}, { num: 139, title: 'Word Break',                              path: '/problems/word-break',                             difficulty: 'Medium', category: 'Dynamic Programming'}]},
  { day: 12, label: 'DP IV',              problems: [{ num: 1143,title: 'Longest Common Subsequence',         path: '/problems/lcs',                                    difficulty: 'Medium', category: 'Dynamic Programming'}, { num: 718, title: 'Max Length of Repeated Subarray',         path: '/problems/lcss',                                   difficulty: 'Medium', category: 'Dynamic Programming'}]},
  { day: 13, label: 'DP V',               problems: [{ num: 91,  title: 'Decode Ways',                        path: '/problems/decode-ways',                            difficulty: 'Medium', category: 'Dynamic Programming'}, { num: 377, title: 'Combination Sum IV',                      path: '/problems/combination-sum-iv',                     difficulty: 'Medium', category: 'Dynamic Programming'}]},
  { day: 14, label: 'Strings I',          problems: [{ num: 125, title: 'Valid Palindrome',                   path: '/problems/valid-palindrome',                       difficulty: 'Easy',   category: 'String'         }, { num: 242,  title: 'Valid Anagram',                           path: '/problems/valid-anagram',                          difficulty: 'Easy',   category: 'String'         }]},
  // Week 3 — Strings + Trees
  { day: 15, label: 'Strings II',         problems: [{ num: 20,  title: 'Valid Parentheses',                  path: '/problems/valid-parentheses',                      difficulty: 'Easy',   category: 'String'         }, { num: 49,   title: 'Group Anagrams',                          path: '/problems/group-anagrams',                         difficulty: 'Medium', category: 'String'         }]},
  { day: 16, label: 'Strings III',        problems: [{ num: 3,   title: 'Longest Substring Without Repeating',path: '/problems/longest-substring-no-repeat',            difficulty: 'Medium', category: 'String'         }, { num: 424,  title: 'Longest Repeating Char Replacement',     path: '/problems/longest-repeating-character-replacement', difficulty: 'Medium', category: 'String'         }]},
  { day: 17, label: 'Strings IV',         problems: [{ num: 5,   title: 'Longest Palindromic Substring',      path: '/problems/longest-palindromic-substring',          difficulty: 'Medium', category: 'String'         }, { num: 647,  title: 'Palindromic Substrings',                 path: '/problems/palindromic-substrings',                 difficulty: 'Medium', category: 'String'         }]},
  { day: 18, label: 'Strings V',          problems: [{ num: 76,  title: 'Minimum Window Substring',           path: '/problems/minimum-window-substring',               difficulty: 'Hard',   category: 'String'         }]},
  { day: 19, label: 'Trees I',            problems: [{ num: 226, title: 'Invert Binary Tree',                 path: '/problems/invert-binary-tree',                     difficulty: 'Easy',   category: 'Tree'           }, { num: 104,  title: 'Maximum Depth of Binary Tree',          path: '/problems/maximum-depth-binary-tree',              difficulty: 'Easy',   category: 'Tree'           }]},
  { day: 20, label: 'Trees II',           problems: [{ num: 100, title: 'Same Tree',                          path: '/problems/same-tree',                              difficulty: 'Easy',   category: 'Tree'           }, { num: 572,  title: 'Subtree of Another Tree',               path: '/problems/subtree-of-another-tree',                difficulty: 'Easy',   category: 'Tree'           }]},
  { day: 21, label: 'Trees III',          problems: [{ num: 235, title: 'Lowest Common Ancestor of BST',      path: '/problems/lca-bst',                                difficulty: 'Easy',   category: 'Tree'           }, { num: 102,  title: 'Binary Tree Level Order Traversal',     path: '/problems/binary-tree-level-order-traversal',      difficulty: 'Medium', category: 'Tree'           }]},
  // Week 4 — Trees + Intervals + Linked Lists
  { day: 22, label: 'Trees IV',           problems: [{ num: 199, title: 'Binary Tree Right Side View',        path: '/problems/binary-tree-right-side-view',            difficulty: 'Medium', category: 'Tree'           }, { num: 1448, title: 'Count Good Nodes in Binary Tree',       path: '/problems/count-good-nodes',                       difficulty: 'Medium', category: 'Tree'           }]},
  { day: 23, label: 'Intervals I',        problems: [{ num: 252, title: 'Meeting Rooms',                      path: '/problems/meeting-rooms',                          difficulty: 'Easy',   category: 'Interval'       }, { num: 56,   title: 'Merge Intervals',                        path: '/problems/merge-intervals',                        difficulty: 'Medium', category: 'Interval'       }]},
  { day: 24, label: 'Intervals II',       problems: [{ num: 57,  title: 'Insert Interval',                    path: '/problems/insert-interval',                        difficulty: 'Hard',   category: 'Interval'       }, { num: 253,  title: 'Meeting Rooms II',                      path: '/problems/meeting-rooms-ii',                       difficulty: 'Medium', category: 'Interval'       }]},
  { day: 25, label: 'Intervals III',      problems: [{ num: 986, title: 'Interval List Intersections',        path: '/problems/interval-list-intersections',            difficulty: 'Medium', category: 'Interval'       }]},
  { day: 26, label: 'Linked Lists I',     problems: [{ num: 206, title: 'Reverse Linked List',                path: '/problems/reverse-linked-list',                    difficulty: 'Easy',   category: 'Linked List'    }, { num: 141,  title: 'Linked List Cycle',                      path: '/problems/detect-cycle-linked-list',               difficulty: 'Easy',   category: 'Linked List'    }]},
  { day: 27, label: 'Linked Lists II',    problems: [{ num: 21,  title: 'Merge Two Sorted Lists',             path: '/problems/merge-two-sorted-lists',                 difficulty: 'Easy',   category: 'Linked List'    }, { num: 19,   title: 'Remove Nth Node From End of List',      path: '/problems/remove-nth-node-end-list',               difficulty: 'Medium', category: 'Linked List'    }]},
  { day: 28, label: 'Linked Lists III',   problems: [{ num: 23,  title: 'Merge K Sorted Lists',               path: '/problems/merge-k-sorted-lists',                   difficulty: 'Hard',   category: 'Linked List'    }]},
  // Week 5 — Matrix + Graph
  { day: 29, label: 'Matrix I',           problems: [{ num: 73,  title: 'Set Matrix Zeroes',                  path: '/problems/set-matrix-zeroes',                      difficulty: 'Medium', category: 'Matrix'         }, { num: 54,   title: 'Spiral Matrix',                          path: '/problems/spiral-matrix',                          difficulty: 'Medium', category: 'Matrix'         }]},
  { day: 30, label: 'Matrix II',          problems: [{ num: 48,  title: 'Rotate Image',                       path: '/problems/rotate-image',                           difficulty: 'Medium', category: 'Matrix'         }, { num: 79,   title: 'Word Search',                            path: '/problems/word-search',                            difficulty: 'Medium', category: 'Matrix'         }]},
  { day: 31, label: 'Graph I',            problems: [{ num: 200, title: 'Number of Islands',                  path: '/problems/number-of-islands',                      difficulty: 'Medium', category: 'Graph'          }, { num: 133,  title: 'Clone Graph',                           path: '/problems/clone-graph',                            difficulty: 'Medium', category: 'Graph'          }]},
  { day: 32, label: 'Graph II',           problems: [{ num: 207, title: 'Course Schedule',                    path: '/problems/course-schedule',                        difficulty: 'Medium', category: 'Graph'          }, { num: 210,  title: 'Course Schedule II',                   path: '/problems/course-schedule-ii',                     difficulty: 'Medium', category: 'Graph'          }]},
  { day: 33, label: 'Graph III',          problems: [{ num: 261, title: 'Graph Valid Tree',                   path: '/problems/graph-valid-tree',                       difficulty: 'Medium', category: 'Graph'          }, { num: 323,  title: 'Number of Connected Components',      path: '/problems/connected-components-undirected-graph',  difficulty: 'Medium', category: 'Graph'          }]},
  { day: 34, label: 'Graph IV',           problems: [{ num: 684, title: 'Redundant Connection',               path: '/problems/redundant-connection',                   difficulty: 'Medium', category: 'Graph'          }, { num: 721,  title: 'Accounts Merge',                        path: '/problems/accounts-merge',                         difficulty: 'Medium', category: 'Graph'          }]},
  { day: 35, label: 'Graph V',            problems: [{ num: 417, title: 'Pacific Atlantic Water Flow',        path: '/problems/pacific-atlantic-water-flow',            difficulty: 'Medium', category: 'Graph'          }, { num: 399,  title: 'Evaluate Division',                    path: '/problems/evaluate-division',                      difficulty: 'Medium', category: 'Graph'          }]},
  // Week 6 — Graph Hard + Heap + Trie + Backtracking
  { day: 36, label: 'Graph VI',           problems: [{ num: 269, title: 'Alien Dictionary',                   path: '/problems/alien-dictionary',                       difficulty: 'Hard',   category: 'Graph'          }, { num: 127,  title: 'Word Ladder',                           path: '/problems/word-ladder',                            difficulty: 'Hard',   category: 'Graph'          }]},
  { day: 37, label: 'Heap I',             problems: [{ num: 347, title: 'Top K Frequent Elements',            path: '/problems/top-k-frequent-elements',                difficulty: 'Medium', category: 'Heap'           }, { num: 295,  title: 'Find Median from Data Stream',         path: '/problems/find-median-from-data-stream',           difficulty: 'Hard',   category: 'Heap'           }]},
  { day: 38, label: 'Heap II',            problems: [{ num: 502, title: 'IPO',                                path: '/problems/ipo',                                    difficulty: 'Hard',   category: 'Heap'           }]},
  { day: 39, label: 'Trie',               problems: [{ num: 208, title: 'Implement Trie (Prefix Tree)',       path: '/problems/implement-trie',                         difficulty: 'Medium', category: 'Trie'           }, { num: 211,  title: 'Design Add and Search Words',          path: '/problems/design-add-search-words',                difficulty: 'Medium', category: 'Trie'           }]},
  { day: 40, label: 'Backtracking I',     problems: [{ num: 78,  title: 'Subsets',                            path: '/problems/subsets',                                difficulty: 'Medium', category: 'Backtracking'   }, { num: 77,   title: 'Combinations',                          path: '/problems/combinations',                           difficulty: 'Medium', category: 'Backtracking'   }]},
  { day: 41, label: 'Backtracking II',    problems: [{ num: 39,  title: 'Combination Sum',                    path: '/problems/combination-sum',                        difficulty: 'Medium', category: 'Backtracking'   }, { num: 46,   title: 'Permutations',                          path: '/problems/permutations',                           difficulty: 'Medium', category: 'Backtracking'   }]},
  // Week 7 — Review
  { day: 42, label: 'Review: Arrays + Strings', problems: [] },
  { day: 43, label: 'Review: DP + Trees',        problems: [] },
  { day: 44, label: 'Review: Graphs + Heaps',    problems: [] },
  { day: 45, label: 'Final Challenge',           problems: [] },
]

const TOTAL_PROBLEMS = DAYS.reduce((acc, d) => acc + d.problems.length, 0)

export default function StudyCalendar45() {
  return (
    <StudyCalendarTemplate
      title="🗓️ 45-Day Blind 75 Study Plan"
      subtitle="All 75 problems — structured across 45 days with review sessions"
      headerGradient="linear-gradient(135deg, #0f2027, #203a43, #2c5364)"
      progressGradient="linear-gradient(90deg, #6366f1, #10b981)"
      days={DAYS}
      totalDays={45}
      breadcrumbs={[
        { label: '← Home', to: '/' },
        { label: '30-Day Plan', to: '/study-calendar' },
      ]}
      extraStats={[
        { label: 'Total Problems', value: TOTAL_PROBLEMS, color: '#93c5fd' },
      ]}
    />
  )
}
